### ISSUE TITLE
Add support for basic auth

### ISSUE THREAD

**Issue by mre** [hello-rust/lychee#18]
Sometimes websites require basic auth to be retrieved.
We should add a flag for basic auth support to lychee.

Maybe something like `--basic-auth "username:password"`.

Hyper (our http client) recently [moved typed headers into a separate crate](https://github.com/hyperium/hyper/issues/1950).

Here is the header we could use ([docs](https://docs.rs/headers/0.3.2/headers/struct.Authorization.html)):

```rust
use headers::Authorization;

let basic = Authorization::basic("username", "password");
```

We could pass that to hyper when we create the client instance.
Pull requests greatly appreciated. Add a comment here if you'd like to work on this.

**Comment by FabianBG** [comment]
Hi @mre, looking to practice some Rust so this looks good, can you assign it to me ?? :D

**Comment by mre** [comment]
Aye it's yours. :clap:

**Comment by FabianBG** [comment]
Pr donne can you review it pls.

**Comment by FabianBG** [comment]
Some problems with fmt y cllippy :P but already fixed

**Comment by mre** [comment]
Resolved by @FabianBG. Yay! 😀
