### ISSUE TITLE
Support relative URLs

### ISSUE THREAD

**Issue by mre** [hello-rust/lychee#3]
I'd like to suport checking relative urls.
Maybe we could add a `base-url` parameter that gets used for relative URLs.
Help wanted.

**Comment by whizsid** [comment]
I like tobwork on this issue. I will send a PR.

**Comment by mre** [comment]
Nice. Have fun @whizsid. 😃

**Comment by mre** [comment]
Ping @whizsid. Are you still working on this? If not that's also fine and I'd just unassign it for now. 😉

**Comment by whizsid** [comment]
Yes. Sorry for the delay. I will send a PR in next 2 days. I think I should use a markdown parser with the existing link checker. Because the existing link checker is not working for relative URLs.
