### ISSUE TITLE
Show the progress interactively with progress bar and in-flight requests (--progress)

### ISSUE THREAD

**Issue by mre** [hello-rust/lychee#4]
Would love to show the progress of checking the URLs with a progress bar like
https://github.com/mitsuhiko/indicatif.

**Comment by xiaochuanyu** [comment]
Would like to take a stab at this.

**Comment by mre** [comment]
It's all yours. ❤️

**Comment by mre** [comment]
Implemented by @xiaochuanyu. 🚀
