### ISSUE TITLE
Exclude private URLs

### ISSUE THREAD

**Issue by mre** [hello-rust/lychee#5]
We should have flags for excluding private, link-local, and loopback hosts.

Basically this means creating the new commandline flags and mapping them to the functions in std::net (linked below):

* `--exclude-private`: [Exclude private addresses](https://doc.rust-lang.org/std/net/struct.Ipv4Addr.html#method.is_private)
* `--exclude-link-local`: [Exclude link-local addresses](https://doc.rust-lang.org/std/net/struct.Ipv4Addr.html#method.is_link_local)
* `--exclude-loopback`: [Exclude loopback](https://doc.rust-lang.org/std/net/struct.Ipv4Addr.html#method.is_loopback)

Newcomers welcome!

**Comment by pawroman** [comment]
I'd be happy to pick this up!

**Comment by mre** [comment]
Go for it @pawroman. It's all yours. 😃
